import = [
  "~/.config/alacritty/citylights.toml"
]

[window]
decorations = "None"
padding = { x = 8, y = 8 }
opacity = 0.05
blur = true
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12
builtin_box_drawing = false
