import = [
  "~/.config/alacritty/iterm.toml"
]

[window]
decorations = "None"
padding = { x = 4, y = 4 }
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal = { family = "Monaspace Neon" }
italic = { family = "Monaspace Neon", style = "Italic" }
size = 12
offset = { x = 0, y = 6 }
