#!/bin/bash
set -ex
cd "$(dirname "$0")"

setup_fish() {
  # Link config files
  mkdir -p ~/.config/fish/
  ln -sf "$(pwd)/fish/config.fish" ~/.config/fish/config.fish
  ln -sf "$(pwd)/fish/fish_plugins" ~/.config/fish/fish_plugins
  ln -sf "$(pwd)/fish/starship.toml" ~/.config/starship.toml

  # Using fish as a login shell can be problematic since it is not POSIX
  # compliant. So instead we make bash call fish for interactive shells.
  ln -sf "$(pwd)/fish/bashrc" ~/.bashrc
  ln -sf "$(pwd)/fish/bashrc" ~/.zshrc

  # Install starship prompt
  if ! which starship; then
    sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
  fi
  
  # Install fisher plugins
  fish -c "curl -sL https://git.io/fisher | source && fisher update"
}

setup_helix() {
  ln -sf "$(pwd)/helix" ~/.config/helix
}

setup_alacritty() {
  ln -sf "$(pwd)/alacritty" ~/.config/alacritty
}

setup_osx() {
  setup_fish
  setup_helix
  
  # Tell iterm2 to use the settings file in `./iterm2`
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$(pwd)/iterm2"
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
  
  # Install vscode configs
  ln -sf "$(pwd)/vscode/keybindings.json" ~/Library/Application\ Support/Code/User/keybindings.json
  ln -sf "$(pwd)/vscode/settings.json" ~/Library/Application\ Support/Code/User/settings.json

  # Install other config files
  ln -sf "$(pwd)/skhdrc" ~/.skhdrc
  ln -sf "$(pwd)/amethyst.yml" ~/.amethyst.yml
}


setup_linux() {
  setup_fish
  setup_helix
}

################################################################################
# Main

main() {
  # Get sudo upfront so we don't need to ask later.
  sudo true

  case $OSTYPE in
  darwin*)
    setup_osx
    ;;
  *)
    setup_linux
    ;;
  esac
  echo "Success"
}
main
