#!/bin/bash
set -e
cd "$(dirname "$0")"

################################################################################
# Common

# Packages with identical names on homebrew/arch/debian
COMMON_PACKAGES=(
  fish
  neovim
  thefuck # Corrects common command mistakes (e.g. prepending sudo)
  tldr    # tldr versins of man pages
  bat     # better cat
  zoxide  # better cd (with fuzzy matching and autojump)
  exa     # better ls
)

# Packages with identical names on homebrew/arch
ARCH_BREW_PACKAGES=(
  "${COMMON_PACKAGES[@]}"
  grc        # generic colorizer for standard commands
  fd         # better find
  less       # Newer version has --mouse support
  git-delta  # Better git diff
  sd         # Better sed
  ripgrep    # Better grep
  procs      # Better ps
  bottom     # Better top
  fzf        # fuzzy finder
  helix      # helix editor
  direnv     # Automatically load env variables in directories
)


################################################################################
# OSX specific

setup_osx() {
  brew install "${ARCH_BREW_PACKAGES[@]}"

  brew tap homebrew/cask-fonts
  brew install --cask \
    font-fira-code
}

################################################################################
# Linux specific

install_arch_packages() {
  pacman -Sy --noconfirm "${ARCH_BREW_PACKAGES[@]}"
}

install_deb() {
  (cd /tmp && rm -f pkg.deb && wget "$1" -O pkg.deb && sudo dpkg -i pkg.deb)
}

install_debian_packages() {
  packages=(
    "${COMMON_PACKAGES[@]}"
    fd-find # better find
  )
  sudo apt install --yes "${packages[@]}"

  # Packages not available in repositories
  install_deb http://kassiopeia.juls.savba.sk/~garabik/software/grc/grc_1.12-1_all.deb
  install_deb https://github.com/dandavison/delta/releases/download/0.12.1/git-delta_0.12.1_amd64.deb
  install_deb https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  install_deb https://github.com/ClementTsang/bottom/releases/download/0.6.8/bottom_0.6.8_amd64.deb
  install_deb https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor/+files/helix_23.10-1~ubuntu23.04~ppa1_amd64.deb
}

setup_linux() {
  if command -v pacman >/dev/null; then
    install_arch_packages
  fi
  if command -v apt-get >/dev/null; then
    install_debian_packages
  fi
}

################################################################################
# Main

main() {
  # Get sudo upfront so we don't need to ask later.
  sudo true

  case $OSTYPE in
  darwin*)
    setup_osx
    ;;
  *)
    setup_linux
    ;;
  esac
  echo "Success"
}
main
