#!/bin/bash

container=$1
image=$1-image
volume=$1-workspace
volume_vscode=$1-vscode
target=$1
dotfiles=$(dirname "$0")/../

if ! docker volume inspect "$volume" > /dev/null; then
  echo "Creating volume $volume"
  docker volume create "$volume"
fi

if ! docker volume inspect "$volume_vscode" > /dev/null; then
  echo "Creating volume $volume_vscode"
  docker volume create "$volume_vscode"
fi


echo "Building image $image in $dotfiles"
docker build \
  "$dotfiles" \
  -f containers/Dockerfile \
  --target "$target" \
  -t "$image"

if docker container inspect "$container" > /dev/null; then
  echo "Stopping container $container"
  docker rm --force "$container"
fi

echo "Starting container $container"
docker run -dt --rm \
  --volume "$volume:/workspace" \
  --volume "$volume_vscode:/root/.vscode-server" \
  --volume "$dotfiles:/root/dotfiles" \
  --volume "/Volumes:/Volumes" \
  --name "$container" \
  "$image"
