source $(dirname $0)/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle thefuck
antigen bundle z
antigen bundle git

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src

antigen theme af-magic

antigen apply