format = """
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$custom\
$line_break\
$jobs\
$time\
$status\
$hostname\
$character"""

[hostname]
format = "$hostname "
